replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

ingress:
  hosts:
    - host: chat.example.com  # TODO
      paths:
        - path: /
          pathType: ImplementationSpecific