{{- if .Values.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chat-core.fullname" . }}
  labels:
    {{- include "chat-core.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "chat-core.selectorLabels" . | nindent 6 }}
{{- end }}